version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
environment:
  SQL_PASSWORD: some!Password
services: mssql2016
install:
- ps: >-
    iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex

    choco install elixir -version 1.3.4

    refreshenv
build_script:
- cmd: >-
    refreshenv

    C:\ProgramData\chocolatey\lib\Elixir\bin\mix.bat local.hex --force

    C:\ProgramData\chocolatey\lib\Elixir\bin\mix.bat local.rebar --force

    C:\ProgramData\chocolatey\lib\Elixir\bin\mix.bat deps.get
test_script:
- cmd: >-
    refreshenv

    C:\ProgramData\chocolatey\lib\Elixir\bin\mix.bat test